#!/usr/bin/expect 

set user [lindex $argv 0]
set host [lindex $argv 1]
set passwd [lindex $argv 2]
set vdom  [lindex $argv 3]
set ip [lindex $argv 4]


spawn /usr/bin/ssh $user@$host
expect "password:"
send -- "$passwd\r"
expect "#"
send -- "config vdom\r"
expect "(vdom) #"
send -- "edit $vdom\r"
expect "($vdom) #"
send -- "diagnose user banned-ip delete src4 $ip\r"
expect "($vdom) #"
send -- "next\r"
expect "(vdom) #"
send -- "end\r"
expect "#"
send -- "exit\r"
